language: node_js
node_js:
  - "0.12.7"
sudo: false
before_install:
  - npm install -g grunt-cli
notifications:
services:
before_script:
deploy:
  - provider: elasticbeanstalk
    app: "WS-API"
    env: "dev-au-api-ws-web-a"
    on:
      branch: "develop"
    region: "ap-southeast-2"
    access_key_id:
      secure: "L3jtwwEc9tj+/3cfH9TwxXYgZmTjEDH+DmAn18ckUjd8eHrkRVvt9gwMj5TRrusngVQ7Dcj4qh/o0FlXvU6ZCWZrl7mROismAtz/8nZrg+SVFsb5wCdDO7WUAN/jPuawP0ICDXUYI9abQlpXdKE5FFidgdr19eNzRxiojOAPsBegtjmT0hQapnbTzqynO7hoNyypQgvc3zuF3Z70wgm1dO8OPr9QQ00s6BCdrKE5FB2Qbc8ARyRwl72mMJAQVyn/YYDJ4aDOf0ahtGmX3ATvbzubGb/MyaufBVBYbAXzq7cjWckiRotQuFn4MM6VXeiS/Yw+/Fu/W6hbZC2JpROKfGOetl2+i61wuQIxqmDTlaUVHGgb3eoX/yF/hKmHpCv/KG4FvGzlora4/fjU9K7H6qQTelRH6BIykOMd62LCesJmc1Kk/hnH0HZp3p9sSgv6yi1aiCfIziRSs5fBe5zPn4EgQeOWonEfbrfQyKCBoJerL9VNSOFRjarZy353VAgYNjIut/rrMjZWHCafIqW2Kvsa7lsfdSemN8oka6Sa0jiXyD0Nv+UQVcdA+7NbBsHGHCVN5X677E90k6OvbO1o256cWXO0R0wba/gnddl29h93rjeXFkXWRaFLbnImdVHVXqsIgVuKVTEhYvxUJKxpV5g4qpPtwvXcIr82Q5LeLww="
    secret_access_key:
      secure: "Mq/D1kat+hAEtHVP1xUs4s6xTT+hJ9MXCuGOszAk/QIyJgYuqhY8f6Gd7EUo+RTHBUTaYdww2SsyVIXakytuDUM/aU4z/9fPDrHYKU1NsZ4Y7B+Y7L+RXnELrekgd783FCCqE5sA0M14SjkA0AlGj2cBAnKYRZ2I30bLSOLeJiDhBMZ/gXZtgNg7TGUvHZrshii15YqvSSVcW1ZiThY53+ZLO7ialvixRnsRlTKbJ4T8JP2qQIygRhPW98OyoujaHYe/nroM/OmNWpUrogyCq4TtNL6Nl4kWd9DAFk8xc4yaxTrxye4HefSper0rc9HLjeKIVC2TpF3yT9YV/GA9+1E0DowlZQeZmBC9yJeMqPd7+1D4eRztn0t/cGg8aba0nI784YAUOm6OeClGFFMr0VdjOWzuVq/ta7sDG6y0ZcgufBccFFS9RQqyEJQh3zYzJkLS4TeKQLRIcrb4yZCFIysJaiCst/jewSpjff8e2wr7wA/yfV/ymSLmGRuNnu3T/6gWdBlhor5O1wcQ1kjoaUUuX097u8+9CanLQh97J3TQJ3h/77to54mGspd6uJGysd3x0HvNNtK8iQl7XFdnhfDFPXMa049x29YdpGD6fmiF199p0/a8dpUEtan3ri8t7908Hvx/VtG+wqQ3/y1EvffOx+tUDSFR4Ce5EQ+FJqE="
    skip_cleanup: true
    bucket_name: "elasticbeanstalk-ap-southeast-2-981939279353"